'use strict';

/********************************
 **** Managing all the models ***
 ********* independently ********
 ********************************/
module.exports = {
    // BlogModel: require('./blogModel'),
    // BlogCategoryModel: require('./blogCategoryModel'),
    // CategoryModel: require('./categoryModel'),
    // ContactUsModel: require('./contactUsModel'),
    ConversationModel: require('./conversationModel'),
    ConversationRoomModel: require('./conversationRoomModel'),
    // CountryModel: require('./countryModel'),
    // CurrencyModel: require('./currencyModel'),
    // DBVersionModel: require('./dbVersionModel'),
    // DomainModel: require('./domainModel'),
    // DurationModel: require('./durationModel'),
    // ErrorModel: require('./errorModel'),
    // GameChangeHistoryModel: require('./gameChangeHistoryModel'),
    // GameLogModel: require('./gameLogModel'),
    // GameModel: require('./gameModel'),
    // GamePayTableModel: require('./gamePayTableModel'),
    // GamePrizeLevelsModel: require('./gamePrizeLevelsModel'),
    // GamePrizeModel: require('./gamePrizeModel'),
    // GameThemeModel: require('./gameThemeModel'),
    // GameTypeModel: require('./gameTypeModel'),
    // InfoVideoModel: require('./infoVideoModel'),
    // GameSpinModel: require('./gameSpinModel'),
    // InviteHistoryModel: require('./inviteHistoryModel'),
    // JurisdictionModel: require('./jurisdictionModel'),
    // LanguageModel: require('./languageModel'),
    // LogModel: require('./logModel'),
    // LotteryGameWinnerModel: require('./lotteryGameWinnigModel'),
    // LottoNumberModel: require('./lottoNumberModel'),
    // LottoPendingResultModel: require('./lottoPendingResultModel'),
    // LottoPendingRaffleTicketModel: require('./lottoPendingRaffleTicketModel'),
    // MoneyTypeModel: require('./moneyTypeModel'),
    // MusicModel: require('./musicModel'),
    // NewsLetterModel: require('./newsLetterModel'),
    // NotificationModel: require('./notificationModel'),
    // PaylineAnimationModel: require('./paylineAnimationModel'),
    // PendingTimeoutsModel: require('./pendingTimeoutsModel'),
    // PokerPaylineModel: require('./pokerPaylineModel'),
    // PokerRoundModel: require('./pokerRoundModel'),
    // PokerSuitsModel: require('./pokerSuitsModel'),
    // PokerTableModel: require('./pokerTableModel'),
    // PrizeModel: require('./prizeModel'),
    // PrizeTypeModel: require('./prizeTypeModel'),
    // ReferralModel: require('./referralModel'),
    // RouletteTableModel: require('./rouletteTableModel'),
    // RtpWinningPaylineModel: require('./rtpWinningPaylineModel'),
    // SessionModel: require('./sessionModel'),
    // SubscriptionModel: require('./subscriptionModel'),
    // SymbolsModel: require('./symbolsModel'),
    // TokenModel: require('./tokenModel'),
    // TransactionModel: require('./transactionModel'),
    // TransactionTypeModel: require('./transactionTypeModel'),
    // UserAmountSpendModel: require('./userAmountSpendModel'),
    // UserCategoryModel: require('./userCategoryModel'),
    // UserGameLogModel: require('./userGameLogModel'),
    // UserLotteryWinnerModel: require('./userLotteryWinningModel'),
    // UserModel: require('./userModel'),
    // UserPermissionModel: require('./userPermissionModel'),
    // UserRiskCategoryModel: require('./userRiskCategoryModel'),
    // UserRouletteBetModel: require('./userRouletteBetModel'),
    // UserWalletModel: require('./userWalletModel'),
    // UserWinningStatsModel: require('./userWinningStatsModel'),
    // VendorModel: require('./vendorModel'),
    // WinTableModel: require('./winTableModel'),
};